site_name: KSFramework Documentation
theme: readthedocs

extra:
    version: 0.9
pages:
    - [index.md, "简介", "KSFramework介绍"]
    - [overview/install.md, "简介", "安装"]
    - [overview/why.md, "简介", "项目的由来"]
    - [overview/structure.md, "简介", "模块结构组织"]
    - [overview/features.md, "简介", "功能特性"]

    - [quickstart.md, "【快速入门指南！】"]

    - [basic/config.md, "基础约定", "Ini配置文件"]
    - [basic/file-structure.md, "基础约定", "文件目录结构"]

    - [setting/guide.md, "配置表模块", "策划指南：配置表的使用"]
    - [setting/condition-compile.md, "配置表模块", "配置表的条件编译"]
    - [setting/lazy-load.md, "配置表模块", "惰式加载"]
    - [setting/tsv-instead-excel.md, "配置表模块", "使用TSV，不用Excel作为源表"]
    - [setting/custom-table-reader.md, "配置表模块", "自定义与扩展配置表的解析"]

    - [resource/guide.md, "资源模块", "使用资源模块打包、加载"]
    - [resource/debug.md, "资源模块", "资源实时调试监控"]
    - [resource/gc.md, "资源模块", "垃圾回收机制"]

    - [ui/guide.md, "UI模块", "UI模块使用指南"]
    - [ui/ui-binding.md, "UI模块", "控件与变量绑定"]
    - [ui/data-binding.md, "UI模块", "单向数据绑定"]

    - [scripting/functions.md, "脚本指南", "Lua内置函数列表"]
    - [scripting/cookie.md, "脚本指南", "Cookie状态缓存"]
    - [scripting/lua-module.md, "脚本指南", "将Lua脚本模块化"]

    - [hotreload/setting.md, "热重载", "配置表热重载"]
    - [hotreload/assetbundle.md, "热重载", "Asset Bundle热重载"]
    - [hotreload/ui.md, "热重载", "UI热重载"]
    - [hotreload/code.md, "热重载", "其它代码热重载"]

    - [advanced/seperate-unity-projects.md, "开发经验", "使用两个Unity工程"]
    - [advanced/versioning.md, "开发经验", "版本号与版本管理"]
    - [advanced/excel-diff.md, "开发经验", "Excel如何进行SVN协作、差异比较？"]
    - [advanced/app-compile.md, "开发经验", "编译客户端时的内部细节"]
    - [advanced/autoupdate.md, "开发经验", "资源包更新"]
    - [advanced/script-reload.md, "开发经验", "Lua脚本热重载，内存状态数据丢失？"]
    - [advanced/editor.md, "开发经验", "编辑器强化"]
    - [advanced/roles.md, "开发经验", "假定角色需求"]

    - [license.md, "其它", "版权说明"]
    - [roadmap.md, "其它", "开发计划"]
